### ISSUE TITLE
Регистрация -> Вход (тестовый сайт)

### ISSUE THREAD

**Issue by login2030** [codedojo/codedojo#19]
цепочка действий:
1) Регистрация (логин login2030 пароль 123456)
2) перекинуло на страницу входа
3) Пытаюсь войти - просто перезагружается страница и все

**Comment by olegpolyakov** [comment]
Он создал пользователя! Попробуй зайти. У меня получилось зайти по логин login2030 пароль 123456.

**Comment by olegpolyakov** [comment]
Только что попробовал зарегиться - получилось! Попробуй еще раз, я удалю того пользователя.

**Comment by login2030** [comment]
У меня не заходит. Просто страница перезагружается и все. Я попробовал 2 раза зарегаться на одно и то же имя и не получил никакой ошибки, так и должно быть? Видос бы снял, но программа не запускается
