### ISSUE TITLE
Не работает flash-сообщение при попытке начать курс без входа

### ISSUE THREAD

**Issue by login2030** [codedojo/codedojo#9]
![2016-10-02_21-34-38](https://cloud.githubusercontent.com/assets/11016617/19022037/2dd3ac6c-88e8-11e6-8f54-91f85fa7dc78.jpg)
Когда еще не залогинен, и не начал курс, то список видео есть, но при клике на них просто перезагружается текущая страница. Неплохо бы в такой ситуации намекать юзеру, мол это только список уроков, курс сперва нужно начать! По тому, что не все поймут, что его нужно именно начать, а не смотреть с любого видео. А, ну и сама кнопка начать не работает, если это еще кого-то интересует =)

**Comment by olegpolyakov** [comment]
Для просмотра видео необходимо войти. Почему-то не работают flash-сообщение. Оно такое большое и его трудно не заметить)
